// <auto-generated />
using System;
using Alumni_Network_Portal_BE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alumni_Network_Portal_BE.Migrations
{
    [DbContext(typeof(AlumniNetworkDbContext))]
    [Migration("20221020080904_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Alumni_Network_Portal_BE.Models.Domain.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AllowGuests")
                        .HasColumnType("bit");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowGuests = true,
                            AuthorId = 2,
                            Description = "Halloween? Hello Wine! Get ready for a spooky and fun night!",
                            EndTime = new DateTime(2022, 10, 29, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8841),
                            Name = "Halloween Party",
                            StartTime = new DateTime(2022, 10, 29, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AllowGuests = true,
                            AuthorId = 2,
                            Description = "The Noroff course presentation of the case project",
                            EndTime = new DateTime(2022, 10, 28, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8846),
                            Name = "Project Presentation",
                            StartTime = new DateTime(2022, 10, 28, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AllowGuests = true,
                            AuthorId = 2,
                            Description = "Get your socks on and rock on! The case period is over and we need to forget everything we have learned",
                            EndTime = new DateTime(2022, 10, 28, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8849),
                            Name = "After Work Beer",
                            StartTime = new DateTime(2022, 10, 28, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AllowGuests = true,
                            AuthorId = 2,
                            Description = "Come to Festplassen, Bergen to celebrate the best norwegian music!",
                            EndTime = new DateTime(2023, 7, 5, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8851),
                            Name = "Vg Lista topp 20",
                            StartTime = new DateTime(2023, 7, 5, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AllowGuests = true,
                            AuthorId = 2,
                            Description = "Haaland won't stop scoring goals. Complain about at Fredrik's apartment",
                            EndTime = new DateTime(2022, 11, 1, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8853),
                            Name = "Fantasy Permier League Weekly Recap",
                            StartTime = new DateTime(2022, 11, 1, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AllowGuests = true,
                            AuthorId = 2,
                            Description = "Laksevåg has set new routes so we are going exploring!",
                            EndTime = new DateTime(2022, 11, 2, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8861),
                            Name = "Bouldering in Laksevåg",
                            StartTime = new DateTime(2022, 11, 2, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AllowGuests = false,
                            AuthorId = 2,
                            Description = "Today we are ranking up!",
                            EndTime = new DateTime(2022, 10, 28, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8863),
                            Name = "5 man queue",
                            StartTime = new DateTime(2022, 10, 28, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AllowGuests = false,
                            AuthorId = 2,
                            Description = "Trivia, beer and atmosphere!",
                            EndTime = new DateTime(2022, 11, 3, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8865),
                            Name = "Thursday Quiz at Finnegans",
                            StartTime = new DateTime(2022, 11, 3, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AllowGuests = true,
                            AuthorId = 2,
                            Description = "VestBrygg is hosting a beginners course in brewing your own beer. ",
                            EndTime = new DateTime(2022, 10, 31, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8868),
                            Name = "Learn To brew your own beer!",
                            StartTime = new DateTime(2022, 10, 31, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AllowGuests = true,
                            AuthorId = 2,
                            Description = "Get together to share knitting recepies and inspire eachother. There will be tea and cookies ;)",
                            EndTime = new DateTime(2022, 10, 30, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8871),
                            Name = "Knitting and chatting",
                            StartTime = new DateTime(2022, 10, 30, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Alumni_Network_Portal_BE.Models.Domain.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Body")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "We learn about C#",
                            IsPrivate = false,
                            Title = "C# learning group"
                        },
                        new
                        {
                            Id = 2,
                            Body = "The Noroff group",
                            IsPrivate = false,
                            Title = "Noroff"
                        },
                        new
                        {
                            Id = 3,
                            Body = "For members of Experis",
                            IsPrivate = true,
                            Title = "Experis Academy"
                        },
                        new
                        {
                            Id = 4,
                            Body = "Anyone can be part of this group",
                            IsPrivate = false,
                            Title = "Group for everyone"
                        },
                        new
                        {
                            Id = 5,
                            Body = "Discuss and compete in Experis' own Fantasy Premier League",
                            IsPrivate = true,
                            Title = "Fantasy Premier League Experis"
                        },
                        new
                        {
                            Id = 6,
                            Body = "Group to coordinate bouldering events",
                            IsPrivate = false,
                            Title = "Bouldering in Bergen"
                        },
                        new
                        {
                            Id = 7,
                            Body = "Is Kai'sa letting you down lately? Join this group learn why you should play Ezreal",
                            IsPrivate = false,
                            Title = "League of Legends gaming group"
                        },
                        new
                        {
                            Id = 8,
                            Body = "How tall is Mt Everest? How deep is the Mariana Trench? If you know these answers join Quizzy McQuizface for a good time",
                            IsPrivate = true,
                            Title = "Freddy and the Quizzy McQuizface"
                        },
                        new
                        {
                            Id = 9,
                            Body = "We got the ingredients, the equipment, and the knowledge. You got the palate for high quality homebrewed Ipa. So HOP along and join our quest for the cleanest belgian triple.",
                            IsPrivate = false,
                            Title = "VestBrygg Bergen Homebrewing AS"
                        },
                        new
                        {
                            Id = 10,
                            Body = "Do you smell of yarn and listening to podcasts while knitting away. This is place for you to get the best deals on habidasheries.",
                            IsPrivate = false,
                            Title = "Bergen Husflid"
                        });
                });

            modelBuilder.Entity("Alumni_Network_Portal_BE.Models.Domain.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasMaxLength(525)
                        .HasColumnType("nvarchar(525)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("RecieverId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("EventId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ParentId");

                    b.HasIndex("RecieverId");

                    b.HasIndex("TopicId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Body = "CSharp variables needs to be delcared do to it being a strongly typed language. boolean: true or false, char: single character, int: whole number, float: floating point number, double, like float but more accurate, long: like int but bigger, decimal: monetary values.",
                            GroupId = 1,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8414),
                            Title = "Know your variables"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Body = "int [] ages = new int[8] is the declaration for integer array of set length 8. Remember they are zero indexed! Access the second element like this: ages[1].",
                            GroupId = 1,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8445),
                            Title = "Know your arrays"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Body = "Dictionary<int,string> dictionaryOfWords = new Dictionary<int,string>(); is the declaration of key type integer and value type string. It is of dynamic length. add like this: dictionaryOfWords.Add(423, \"First word\"); and access like this dictionaryOfWords(423).",
                            GroupId = 1,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8447),
                            Title = "Know your dictionaries"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Body = "A class is made of four components. Constructors, fields, bahaviours and properties",
                            GroupId = 1,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8449),
                            Title = "Know your Class"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            Body = "The Firealarm might go off today due to technical issues",
                            GroupId = 2,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8451),
                            Title = "Firealarm might go off today!"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            Body = "Monday: Bean Shepards Pie, Tuesday: Baked Cod, Wednesday: Chickpea Masala, Thursday: Lentils Lansagna, Friday: Loaded Veggie Taco",
                            GroupId = 2,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8454),
                            Title = "Weekly menu in the cafeteria"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            Body = "I have been trying to get enpoints to work, but they just wont work!",
                            GroupId = 3,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8456),
                            Title = "Anyone know how endpoints work?"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 1,
                            Body = "Have you tried adding scoped of the services?",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8458),
                            ParentId = 7
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 3,
                            Body = "Checkout the noroff page to see how to correctly set up controller and services",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8460),
                            ParentId = 7
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 1,
                            Body = "If anyone is interested, just ask me",
                            GroupId = 3,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8464),
                            Title = "I figured out how to get figma to work"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 1,
                            Body = "Figma balls",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8469),
                            ParentId = 10
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 1,
                            Body = "Save electricity in these dark times",
                            GroupId = 3,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8471),
                            Title = "Remember to turn off the lights when leaving the offices"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 2,
                            Body = "They have automatic movement sensors, so theres no stress",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8473),
                            ParentId = 12
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 1,
                            Body = "Use it for all your social media needs!",
                            GroupId = 4,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8475),
                            Title = "Alumni Network is the best app out there!"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 2,
                            Body = "The change we need in social media",
                            GroupId = 4,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8482),
                            Title = "Thank you for using Almuni Network!"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 3,
                            Body = "The man keeps assisting and scoring points, hes def worth the high price",
                            GroupId = 5,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8484),
                            Title = "I decided to add Kevin De Bruyne"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 4,
                            Body = "Arsenal definitely seems to have turned things around this season",
                            GroupId = 5,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8486),
                            Title = "Is Arteta the must-have-coach"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 3,
                            Body = "Cheaper than Pep and gets as many points, but doubt he can keep it up through this season",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8489),
                            ParentId = 17
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 2,
                            Body = "I have him on my team, but after the world cup i might change it to Klopp. He'll have a hell of a second half of the season.",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8491),
                            ParentId = 17
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 3,
                            Body = "I have Mancini, fml",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8493),
                            ParentId = 17
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 4,
                            Body = "Holy guacamoly, I ahave never had so many points in a round before!",
                            GroupId = 5,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8495),
                            Title = "This round scored me so many points!"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 4,
                            Body = "I was so stressed, when I heard the rumors",
                            GroupId = 5,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8497),
                            Title = "Praise the Lord, Allahu Ackbar, and Barukh Hashem! Haaland is not injured!"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 4,
                            Body = "So crazy that guy",
                            GroupId = 6,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8499),
                            Title = "Did you guys see Magnus midtbø's newest video?"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 3,
                            Body = "I heard they will have 700 meters of climbing!",
                            GroupId = 6,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8501),
                            Title = "I am so looking forward to the new bouldering hall in Åsane!"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 1,
                            Body = "I have no idea how it is the most popular character!",
                            GroupId = 7,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8503),
                            Title = "Kai'sa is so overrated"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 1,
                            Body = "It always delivers in creating a balanced game!",
                            GroupId = 7,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8505),
                            Title = "ARAM is the best gamemode"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 1,
                            Body = "I want to watch this years worlds",
                            GroupId = 7,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8507),
                            Title = "When is Worlds?"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 3,
                            Body = "It has already been, i am sorry",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8509),
                            ParentId = 27
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 3,
                            Body = "Maybe you can watch the replays on youtube",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8511),
                            ParentId = 27
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 1,
                            Body = "Mine is Lee Sin",
                            GroupId = 7,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8513),
                            Title = "What is your favourite character?"
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 3,
                            Body = "Mine is Teemo!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8515),
                            ParentId = 29
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 3,
                            Body = "I just get rekt :( ",
                            GroupId = 7,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8517),
                            Title = "I don't want to play toplane anymore!"
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 2,
                            Body = "I know all the capitals of European and American countries",
                            GroupId = 8,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8520),
                            Title = "I have read up on geography"
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 2,
                            Body = "I feel this is the subject we get the least points on",
                            GroupId = 8,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8574),
                            Title = "We need to get some knowledge on litterature"
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 3,
                            Body = "I mean, it is the most boring subject of all",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8577),
                            ParentId = 34
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 2,
                            Body = "Next time we will get them!",
                            GroupId = 8,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8580),
                            Title = "We are tied with Conquiztadores for second place overall"
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 3,
                            Body = "Heck yeah we will!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8582),
                            ParentId = 36
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 3,
                            Body = "Get your hops on now, all hops from the 2021 season is 20% off all week!",
                            GroupId = 9,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8583),
                            Title = "Cheap HOPS! 20% off all week!"
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 3,
                            Body = "Tasty and aromatic, hints of chocolate and coffee. Beautiful mouthfeel!",
                            GroupId = 9,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8585),
                            Title = "Congratulations to Tom for brewing the best stout in our fall-brew-off!"
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 3,
                            Body = "We have made a ten step guide to how to create the best NEIPA!",
                            GroupId = 9,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8588),
                            Title = "Keen on a proper New England IPA? Come by our store to get the best tips and tricks!"
                        },
                        new
                        {
                            Id = 41,
                            AuthorId = 3,
                            Body = "Get them at our store, for favourable prices and good insight in yeast culture.",
                            GroupId = 9,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8590),
                            Title = "Use Norwegian yeast Kveik to brew your pale ales!"
                        },
                        new
                        {
                            Id = 42,
                            AuthorId = 4,
                            Body = "Page 3 in the Husflid catalogue. How does that make sense?",
                            GroupId = 10,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8592),
                            Title = "Anyone understand this knitting recipe, and can help me out?"
                        },
                        new
                        {
                            Id = 43,
                            AuthorId = 3,
                            Body = "3x4 =12 and increase by one each round for 8 rounds to get 20. I think..",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8594),
                            ParentId = 42
                        },
                        new
                        {
                            Id = 44,
                            AuthorId = 4,
                            Body = "Thinking something green",
                            GroupId = 10,
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8596),
                            Title = "What are your favorite colors for winter gowns. I want to sow my own!"
                        },
                        new
                        {
                            Id = 45,
                            AuthorId = 3,
                            Body = "The darker themes of SelfMade are astonishing!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8599),
                            ParentId = 44
                        },
                        new
                        {
                            Id = 46,
                            AuthorId = 2,
                            Body = "The demonstrations erupted nearly a month ago over the death of 22-year-old Mahsa Amini in police custody",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8600),
                            Title = "Protests in Iran: 'The younger generation are starting a revolution'",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 47,
                            AuthorId = 2,
                            Body = "Prized for the lightweight, elastic bark, cork oaks can also store large amounts of carbon during their long lifetimes. Now there are moves to find new uses for this material.",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8603),
                            Title = "Why cork is making a comeback",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 48,
                            AuthorId = 2,
                            Body = "England missed the chance to complete a series clean sweep over Australia when their third Twenty20 match in Canberra was abandoned because of rain.",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8605),
                            Title = "England in Australia: Third Twenty20 abandoned because of rain in Canberra",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 49,
                            AuthorId = 2,
                            Body = "Between 1809 and 1814 the island became a prison for 11,000 defeated Napoleonic soldiers. Conditions were grim and up to 5,000 were estimated to have died of starvation, dehydration, and various illnesses.",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8607),
                            Title = "Cabrera: The heavenly island that became hell on earth",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 50,
                            AuthorId = 2,
                            Body = "Kwasi Kwarteng - who is out of his job as the UK's chancellor - has just confirmed that he was sacked by Prime Minister Liz Truss rather than choosing to leave.",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8609),
                            Title = "Kwarteng confirms he was asked to 'stand aside'",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 51,
                            AuthorId = 1,
                            Body = "The woman walks to the rear of the bus and sits down, fuming. She says to a man next to her: “The driver just insulted me!” The man says: “You go up there and tell him off. Go on, I’ll hold your monkey for you.”",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8611),
                            Title = "A woman gets on a bus with her baby. The bus driver says: 'Ugh, that’s the ugliest baby I’ve ever seen!'",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 52,
                            AuthorId = 2,
                            Body = "Haha, great one!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8613),
                            ParentId = 51
                        },
                        new
                        {
                            Id = 53,
                            AuthorId = 1,
                            Body = "He said, 'How flexible are you?' I said, 'I can’t make Tuesdays.'",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8615),
                            Title = "I said to the Gym instructor 'Can you teach me to do the splits?'",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 54,
                            AuthorId = 2,
                            Body = "Haha, great one!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8618),
                            ParentId = 53
                        },
                        new
                        {
                            Id = 55,
                            AuthorId = 1,
                            Body = "They charged one – and let the other one off.",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8620),
                            Title = "Police arrested two kids yesterday, one was drinking battery acid, the other was eating fireworks.",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 56,
                            AuthorId = 2,
                            Body = "Haha, great one!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8622),
                            ParentId = 55
                        },
                        new
                        {
                            Id = 57,
                            AuthorId = 1,
                            Body = "I’ve lost three days already.",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8624),
                            Title = "I’m on a whiskey diet.",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 58,
                            AuthorId = 2,
                            Body = "Haha, great one!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8626),
                            ParentId = 57
                        },
                        new
                        {
                            Id = 59,
                            AuthorId = 1,
                            Body = "Isn't that just amazing!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8628),
                            Title = "Fun fact: Fleas can jump 350 times its body length.",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 60,
                            AuthorId = 2,
                            Body = "Isn't that just amazing!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8633),
                            Title = "Fun fact: Hummingbirds are the only birds that can fly backwards.",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 61,
                            AuthorId = 1,
                            Body = "Isn't that just amazing!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8635),
                            Title = "Fun fact: Crocodiles cannot stick their tongue out.",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 62,
                            AuthorId = 2,
                            Body = "Isn't that just amazing!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8637),
                            Title = "Fun fact: Starfish do not have a brain.",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 63,
                            AuthorId = 2,
                            Body = "https://www.bbcgoodfood.com/recipes/caponata-pasta",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8639),
                            Title = "Recipe: Simple Pasta",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 64,
                            AuthorId = 2,
                            Body = "https://www.bbcgoodfood.com/recipes/coconut-squash-dhansak",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8641),
                            Title = "Recipe: Coconut & squash dhansak",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 65,
                            AuthorId = 2,
                            Body = "https://www.bbcgoodfood.com/recipes/veggie-fajitas",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8643),
                            Title = "Recipe: Veggie Fajitas",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 66,
                            AuthorId = 2,
                            Body = "Brown wool caps are hot in every sense of the word",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8646),
                            Title = "Top ten hottest caps right now!",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 67,
                            AuthorId = 3,
                            Body = "I want to find a nice fall cap!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8648),
                            Title = "Anyone now any good places to get caps?",
                            TopicId = 5
                        },
                        new
                        {
                            Id = 68,
                            AuthorId = 2,
                            Body = "Vanity has some nice ones",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8650),
                            ParentId = 67
                        },
                        new
                        {
                            Id = 69,
                            AuthorId = 2,
                            Body = "Such a cool song!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8652),
                            Title = "I Wanna Be Your Dog – The Stooges",
                            TopicId = 6
                        },
                        new
                        {
                            Id = 70,
                            AuthorId = 1,
                            Body = "I love this song!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8654),
                            ParentId = 69
                        },
                        new
                        {
                            Id = 71,
                            AuthorId = 1,
                            Body = "Proper banger!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8656),
                            Title = "Anarchy in the UK – Sex Pistols",
                            TopicId = 6
                        },
                        new
                        {
                            Id = 72,
                            AuthorId = 2,
                            Body = "I love this song!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8658),
                            ParentId = 71
                        },
                        new
                        {
                            Id = 73,
                            AuthorId = 2,
                            Body = "Such a cool song!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8660),
                            Title = "Self Esteem – The Offspring",
                            TopicId = 6
                        },
                        new
                        {
                            Id = 74,
                            AuthorId = 1,
                            Body = "I love this song!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8662),
                            ParentId = 73
                        },
                        new
                        {
                            Id = 75,
                            AuthorId = 2,
                            Body = "Such a cool song!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8664),
                            Title = "American Idiot – Green Day",
                            TopicId = 6
                        },
                        new
                        {
                            Id = 76,
                            AuthorId = 1,
                            Body = "I love this song!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8666),
                            ParentId = 75
                        },
                        new
                        {
                            Id = 77,
                            AuthorId = 2,
                            Body = "Personally I like pour over best, but what do you guys like?",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8726),
                            Title = "Pour over or french press?",
                            TopicId = 7
                        },
                        new
                        {
                            Id = 78,
                            AuthorId = 1,
                            Body = "I use french press myself, but in weekends I use a Bialetti!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8728),
                            ParentId = 77
                        },
                        new
                        {
                            Id = 79,
                            AuthorId = 1,
                            Body = "My Moccamaster makes just as good cooffee as any other fancy coffee bars",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8730),
                            Title = "Is barrista coffee overrated?",
                            TopicId = 7
                        },
                        new
                        {
                            Id = 80,
                            AuthorId = 2,
                            Body = "Arabica has been the most famous for a long time, but I like RObusta myself.",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8732),
                            Title = "What are the best beans? Arabica or Robusta",
                            TopicId = 7
                        },
                        new
                        {
                            Id = 81,
                            AuthorId = 1,
                            Body = "I like arabica myself!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8734),
                            ParentId = 80
                        },
                        new
                        {
                            Id = 82,
                            AuthorId = 2,
                            Body = "I think they would look nice!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8736),
                            Title = "Should we allow for skyscrapers in Bergen",
                            TopicId = 8
                        },
                        new
                        {
                            Id = 83,
                            AuthorId = 2,
                            Body = "We want Bergen to become the first European city to be properly car free!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8738),
                            Title = "Car free Bergen!",
                            TopicId = 8
                        },
                        new
                        {
                            Id = 84,
                            AuthorId = 4,
                            Body = "People don't know what they talk about. Me neither, to be fair.",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8740),
                            Title = "Bergen politics is bad!",
                            TopicId = 8
                        },
                        new
                        {
                            Id = 85,
                            AuthorId = 4,
                            Body = "I was so upset when he didn't win!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8742),
                            Title = "Spaceman is the best song!",
                            TopicId = 9
                        },
                        new
                        {
                            Id = 86,
                            AuthorId = 3,
                            Body = "I hope GB will deliver in their hosting!",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8744),
                            Title = "I am so looking forward to next years ESC!",
                            TopicId = 9
                        },
                        new
                        {
                            Id = 87,
                            AuthorId = 1,
                            Body = "As Ukraine has been attacked by Russia and is not a safe place currently, it has to be hosted in the UK",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8746),
                            Title = "It has been decided that UK will host the ESC 2023",
                            TopicId = 9
                        },
                        new
                        {
                            Id = 88,
                            AuthorId = 1,
                            Body = "The second byte replies, 'No, just feeling a bit off.'",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8748),
                            Title = "Two bytes meet.  The first byte asks, 'Are you ill?'",
                            TopicId = 10
                        },
                        new
                        {
                            Id = 89,
                            AuthorId = 2,
                            Body = "Haha, great one",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8750),
                            ParentId = 88
                        },
                        new
                        {
                            Id = 90,
                            AuthorId = 1,
                            Body = "'Yeah,' reply the bytes.  'Make us a double.'",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8752),
                            Title = "Eight bytes walk into a bar.  The bartender asks, 'Can I get you anything?'",
                            TopicId = 10
                        },
                        new
                        {
                            Id = 91,
                            AuthorId = 1,
                            Body = "He read the shampoo bottle instructions: Lather. Rinse. Repeat.",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8754),
                            Title = "How did the programmer die in the shower?",
                            TopicId = 10
                        },
                        new
                        {
                            Id = 92,
                            AuthorId = 2,
                            Body = "Haha, great one",
                            LastUpdated = new DateTime(2022, 10, 20, 10, 9, 3, 877, DateTimeKind.Local).AddTicks(8756),
                            ParentId = 91
                        });
                });

            modelBuilder.Entity("Alumni_Network_Portal_BE.Models.Domain.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Body")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Discussion of the latest news around the world",
                            Title = "Worldnews"
                        },
                        new
                        {
                            Id = 2,
                            Body = "Discuss anything that is related to fun things! Got a good joke? Maybe a banger meme? Post it here!",
                            Title = "Fun"
                        },
                        new
                        {
                            Id = 3,
                            Body = "We talk about anything related to animals",
                            Title = "Animals"
                        },
                        new
                        {
                            Id = 4,
                            Body = "Food talk, recipes and anything that involves food",
                            Title = "Food"
                        },
                        new
                        {
                            Id = 5,
                            Body = "The hottest trends in the world of headwear",
                            Title = "Caps and Hats"
                        },
                        new
                        {
                            Id = 6,
                            Body = "Do you have Red Flags? Do you Rage Against The Machine? Are you a Basket Case? Discuss it with us here",
                            Title = "Punk Music"
                        },
                        new
                        {
                            Id = 7,
                            Body = "Java means coffee. Anyone who thinks otherwise is a disillusioned fool. Hot steamed and smoke roast",
                            Title = "Java Beans"
                        },
                        new
                        {
                            Id = 8,
                            Body = "Should the Bybana go above Bryggen. Under? Get the latest Bergen news here",
                            Title = "Bergen Politics"
                        },
                        new
                        {
                            Id = 9,
                            Body = "It is only 7 months until Eurovision 2023 in Liverpool. Get the latest news and discuss them here as the national entries are annouced",
                            Title = "Eurovision Song Contest"
                        },
                        new
                        {
                            Id = 10,
                            Body = "What is he difference between C and C++? One",
                            Title = "Programmer Memes"
                        });
                });

            modelBuilder.Entity("Alumni_Network_Portal_BE.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bio")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FunFact")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Likes french culture",
                            FunFact = "None",
                            KeycloakId = "4f1bd04c-7e5a-406f-952d-756ed92933bc",
                            Status = "Online",
                            Username = "fred"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Likes backend and peaches",
                            FunFact = "None",
                            KeycloakId = "7ccf5453-c488-43f3-b7eb-587d8e44054b",
                            Status = "Online",
                            Username = "olem"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Fan of sodas",
                            FunFact = "None",
                            KeycloakId = "a23f6e10-697d-4f53-bd1d-f38157e3ef54",
                            Status = "Online",
                            Username = "solo"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Mr.Bean lover",
                            FunFact = "None",
                            KeycloakId = "14b7a32e-27a4-488b-89d4-e411bec2ba2f",
                            Status = "Online",
                            Username = "johnny"
                        });
                });

            modelBuilder.Entity("Event_Group", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("Event_Group");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            EventId = 1
                        },
                        new
                        {
                            GroupId = 2,
                            EventId = 2
                        },
                        new
                        {
                            GroupId = 3,
                            EventId = 3
                        },
                        new
                        {
                            GroupId = 4,
                            EventId = 4
                        },
                        new
                        {
                            GroupId = 5,
                            EventId = 5
                        },
                        new
                        {
                            GroupId = 6,
                            EventId = 6
                        },
                        new
                        {
                            GroupId = 7,
                            EventId = 7
                        },
                        new
                        {
                            GroupId = 8,
                            EventId = 8
                        },
                        new
                        {
                            GroupId = 9,
                            EventId = 9
                        },
                        new
                        {
                            GroupId = 10,
                            EventId = 10
                        });
                });

            modelBuilder.Entity("Event_Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.HasKey("TopicId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("Event_Topic");

                    b.HasData(
                        new
                        {
                            TopicId = 2,
                            EventId = 1
                        },
                        new
                        {
                            TopicId = 2,
                            EventId = 3
                        });
                });

            modelBuilder.Entity("EventUserInvitation", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("EventUserInvitation");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            UserId = 1
                        },
                        new
                        {
                            EventId = 1,
                            UserId = 2
                        },
                        new
                        {
                            EventId = 1,
                            UserId = 3
                        },
                        new
                        {
                            EventId = 1,
                            UserId = 4
                        },
                        new
                        {
                            EventId = 2,
                            UserId = 1
                        },
                        new
                        {
                            EventId = 2,
                            UserId = 2
                        },
                        new
                        {
                            EventId = 2,
                            UserId = 3
                        },
                        new
                        {
                            EventId = 2,
                            UserId = 4
                        },
                        new
                        {
                            EventId = 3,
                            UserId = 1
                        },
                        new
                        {
                            EventId = 3,
                            UserId = 2
                        },
                        new
                        {
                            EventId = 3,
                            UserId = 3
                        },
                        new
                        {
                            EventId = 3,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("GroupMember", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMember");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            UserId = 1
                        },
                        new
                        {
                            GroupId = 1,
                            UserId = 2
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = 1
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = 2
                        },
                        new
                        {
                            GroupId = 3,
                            UserId = 1
                        },
                        new
                        {
                            GroupId = 3,
                            UserId = 2
                        },
                        new
                        {
                            GroupId = 3,
                            UserId = 3
                        },
                        new
                        {
                            GroupId = 4,
                            UserId = 1
                        },
                        new
                        {
                            GroupId = 4,
                            UserId = 2
                        },
                        new
                        {
                            GroupId = 5,
                            UserId = 2
                        },
                        new
                        {
                            GroupId = 5,
                            UserId = 3
                        },
                        new
                        {
                            GroupId = 5,
                            UserId = 4
                        },
                        new
                        {
                            GroupId = 6,
                            UserId = 3
                        },
                        new
                        {
                            GroupId = 6,
                            UserId = 4
                        },
                        new
                        {
                            GroupId = 7,
                            UserId = 1
                        },
                        new
                        {
                            GroupId = 7,
                            UserId = 3
                        },
                        new
                        {
                            GroupId = 8,
                            UserId = 2
                        },
                        new
                        {
                            GroupId = 8,
                            UserId = 3
                        },
                        new
                        {
                            GroupId = 9,
                            UserId = 1
                        },
                        new
                        {
                            GroupId = 9,
                            UserId = 3
                        },
                        new
                        {
                            GroupId = 9,
                            UserId = 4
                        },
                        new
                        {
                            GroupId = 10,
                            UserId = 3
                        },
                        new
                        {
                            GroupId = 10,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("RSVP", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RSVP");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            UserId = 1
                        },
                        new
                        {
                            EventId = 1,
                            UserId = 3
                        },
                        new
                        {
                            EventId = 1,
                            UserId = 4
                        },
                        new
                        {
                            EventId = 2,
                            UserId = 1
                        },
                        new
                        {
                            EventId = 2,
                            UserId = 3
                        },
                        new
                        {
                            EventId = 2,
                            UserId = 4
                        },
                        new
                        {
                            EventId = 3,
                            UserId = 1
                        },
                        new
                        {
                            EventId = 3,
                            UserId = 3
                        },
                        new
                        {
                            EventId = 3,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Subscribe_Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TopicId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscribe_Topic");

                    b.HasData(
                        new
                        {
                            TopicId = 1,
                            UserId = 2
                        },
                        new
                        {
                            TopicId = 2,
                            UserId = 1
                        },
                        new
                        {
                            TopicId = 2,
                            UserId = 2
                        },
                        new
                        {
                            TopicId = 3,
                            UserId = 1
                        },
                        new
                        {
                            TopicId = 3,
                            UserId = 2
                        },
                        new
                        {
                            TopicId = 4,
                            UserId = 2
                        },
                        new
                        {
                            TopicId = 4,
                            UserId = 3
                        },
                        new
                        {
                            TopicId = 4,
                            UserId = 4
                        },
                        new
                        {
                            TopicId = 5,
                            UserId = 2
                        },
                        new
                        {
                            TopicId = 5,
                            UserId = 3
                        },
                        new
                        {
                            TopicId = 5,
                            UserId = 4
                        },
                        new
                        {
                            TopicId = 6,
                            UserId = 1
                        },
                        new
                        {
                            TopicId = 6,
                            UserId = 2
                        },
                        new
                        {
                            TopicId = 7,
                            UserId = 1
                        },
                        new
                        {
                            TopicId = 7,
                            UserId = 2
                        },
                        new
                        {
                            TopicId = 7,
                            UserId = 4
                        },
                        new
                        {
                            TopicId = 8,
                            UserId = 2
                        },
                        new
                        {
                            TopicId = 8,
                            UserId = 3
                        },
                        new
                        {
                            TopicId = 8,
                            UserId = 4
                        },
                        new
                        {
                            TopicId = 9,
                            UserId = 1
                        },
                        new
                        {
                            TopicId = 9,
                            UserId = 3
                        },
                        new
                        {
                            TopicId = 9,
                            UserId = 4
                        },
                        new
                        {
                            TopicId = 10,
                            UserId = 1
                        },
                        new
                        {
                            TopicId = 10,
                            UserId = 2
                        },
                        new
                        {
                            TopicId = 10,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Alumni_Network_Portal_BE.Models.Domain.Event", b =>
                {
                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.User", "Author")
                        .WithMany("AuthoredEvents")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Alumni_Network_Portal_BE.Models.Domain.Post", b =>
                {
                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.User", "Author")
                        .WithMany("AuthoredPosts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.Event", "Event")
                        .WithMany("Posts")
                        .HasForeignKey("EventId");

                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.Group", "Group")
                        .WithMany("Posts")
                        .HasForeignKey("GroupId");

                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.Post", "Parent")
                        .WithMany("Replies")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.User", "Reciever")
                        .WithMany("RecievedPosts")
                        .HasForeignKey("RecieverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.Topic", "Topic")
                        .WithMany("Posts")
                        .HasForeignKey("TopicId");

                    b.Navigation("Author");

                    b.Navigation("Event");

                    b.Navigation("Group");

                    b.Navigation("Parent");

                    b.Navigation("Reciever");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Event_Group", b =>
                {
                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Event_Topic", b =>
                {
                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventUserInvitation", b =>
                {
                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupMember", b =>
                {
                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RSVP", b =>
                {
                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Subscribe_Topic", b =>
                {
                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alumni_Network_Portal_BE.Models.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Alumni_Network_Portal_BE.Models.Domain.Event", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Alumni_Network_Portal_BE.Models.Domain.Group", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Alumni_Network_Portal_BE.Models.Domain.Post", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Alumni_Network_Portal_BE.Models.Domain.Topic", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Alumni_Network_Portal_BE.Models.Domain.User", b =>
                {
                    b.Navigation("AuthoredEvents");

                    b.Navigation("AuthoredPosts");

                    b.Navigation("RecievedPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
